# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TTNetworkDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for TTNetworkDemo
  pod 'AFNetworking', '~> 3.0'

  target 'TTNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
